version: "3.7"
services:
  haproxy:
    container_name: "swarm-haproxy"
    image: stasbar/swarm-haproxy
    restart: "unless-stopped"
    dns: 127.0.0.11
    environment:
      - TDS_PORT=8082
      - KEYBASE_PORT=8083
      - EMAILS_PORT=8084
    ports:
      - 80:80
      - 443:443
    networks:
      - stellot-overlay
      - vapetool-overlay

networks:
  stellot-overlay:
    external: true
    name: stellot-overlay
  vapetool-overlay:
    external: true
    name: vapetool-overlay
